# Generated by Django 3.2.9 on 2021-11-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='wight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
