# Generated by Django 3.2.9 on 2021-11-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman_task', '0002_auto_20211114_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='wight',
            new_name='widht',
        ),
    ]
